version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: pg-commerce
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=commerceapi
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
